const MONTH_NAMES = [
  'January', 'February', 'March', 'April', 'May', 'June',
  'July', 'August', 'September', 'October', 'November', 'December'
];

/**
 * Exports the monthly habit matrix grid into a beautifully formatted .xlsx file.
 *
 * @param {Object} params
 * @param {Array} params.habits List of habit objects
 * @param {number} params.selectedYear 4-digit year
 * @param {number} params.selectedMonth 0-indexed month (0 = Jan, 11 = Dec)
 * @param {Array} params.monthDays Array of day objects generated by HabitMatrixGrid
 * @param {Array} params.dailyStats Daily stats calculated for the footer
 * @param {Function} params.getHabitMonthStats Helper function returning stats for a single habit
 */
export async function exportHabitMatrixToExcel({
  habits = [],
  selectedYear,
  selectedMonth,
  monthDays = [],
  dailyStats = [],
  getHabitMonthStats
}) {
  const XLSX = await import('xlsx');
  const monthName = MONTH_NAMES[selectedMonth] || `Month-${selectedMonth + 1}`;
  const fileName = `TwoGether_${monthName}_${selectedYear}.xlsx`;

  // 1. Build Title & Info rows
  const aoaData = [
    ['TWOGETHER — MONTHLY HABIT TRACKER & GOALS SPREADSHEET'],
    [`Period: ${monthName} ${selectedYear}`, '', '', '', `Exported: ${new Date().toLocaleDateString()}`],
    [] // Empty row spacer
  ];

  // 2. Table Headers
  const headerRow = ['Habit / Goal', 'Category', 'Status', 'Priority'];
  monthDays.forEach((d) => {
    headerRow.push(`${d.dayNum} (${d.dayOfWeek})`);
  });
  headerRow.push('Completed Days', 'Eligible Days', 'Monthly Rate');
  aoaData.push(headerRow);

  // 3. Habit Rows
  habits.forEach((habit) => {
    const stats = getHabitMonthStats ? getHabitMonthStats(habit) : { completedCount: 0, eligibleDays: 0, percent: 0 };
    const row = [
      habit.title || 'Untitled Habit',
      habit.category || 'General',
      habit.status === 'completed' ? 'Concluded Goal' : 'Active Routine',
      (habit.priority || 'medium').toUpperCase()
    ];

    monthDays.forEach((d) => {
      const isCompleted = (habit.completedDates || []).includes(d.dateStr);
      const start = habit.startDate || habit.createdAt?.slice(0, 10);
      const end = habit.endDate || null;

      if (d.isPreJoin || (start && d.dateStr < start) || (end && d.dateStr > end)) {
        row.push('-'); // Out of range or before registration
      } else if (d.isFuture) {
        row.push('·'); // Future day
      } else if (isCompleted) {
        row.push('✓'); // Completed
      } else {
        row.push('0'); // Pending / missed
      }
    });

    row.push(stats.completedCount);
    row.push(stats.eligibleDays);
    row.push(`${stats.percent}%`);
    aoaData.push(row);
  });

  // 4. Spacer row before totals
  aoaData.push([]);

  // 5. Daily Totals Row
  const totalCompletedRow = ['Daily Total Completed', '', '', ''];
  monthDays.forEach((_, idx) => {
    totalCompletedRow.push(dailyStats[idx]?.completed ?? 0);
  });
  const grandTotalCompleted = habits.reduce((acc, h) => {
    const s = getHabitMonthStats ? getHabitMonthStats(h) : { completedCount: 0 };
    return acc + (s.completedCount || 0);
  }, 0);
  totalCompletedRow.push(grandTotalCompleted, '', '');
  aoaData.push(totalCompletedRow);

  // 6. Daily Completion Rate Row
  const completionRateRow = ['Daily Completion Rate (%)', '', '', ''];
  monthDays.forEach((_, idx) => {
    completionRateRow.push(`${dailyStats[idx]?.percent ?? 0}%`);
  });
  completionRateRow.push('', '', '');
  aoaData.push(completionRateRow);

  // 7. Create SheetJS Worksheet & Workbook
  const ws = XLSX.utils.aoa_to_sheet(aoaData);

  // 8. Auto-format column widths
  const colWidths = [
    { wch: 28 }, // Habit Title
    { wch: 14 }, // Category
    { wch: 16 }, // Status
    { wch: 10 }, // Priority
  ];
  // Day columns (e.g. "12 (Mo)" -> ~8 chars width)
  monthDays.forEach(() => {
    colWidths.push({ wch: 7 });
  });
  // Summary columns
  colWidths.push({ wch: 16 }); // Completed Days
  colWidths.push({ wch: 14 }); // Eligible Days
  colWidths.push({ wch: 14 }); // Monthly Rate

  ws['!cols'] = colWidths;

  const wb = XLSX.utils.book_new();
  const safeSheetName = `${monthName} ${selectedYear}`.slice(0, 31);
  XLSX.utils.book_append_sheet(wb, ws, safeSheetName);

  // 9. Download Excel File
  XLSX.writeFile(wb, fileName);
}
